jobs:
  - name: film_revenue_transform
    schedule:
      type: integrated
      integrations:
        - mandible_balm
    steps:
      - name: run models
        command: dbt run --models film_revenue_performance
      - name: test models
        command: dbt test --models film_revenue_performance
